# Generated by Django 3.2.8 on 2021-10-12 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0003_whish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whish',
            new_name='Wish',
        ),
    ]
